core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hawan/',include("hawan.urls"))
]

hawan/urls.py
from django.urls import path
from . import views
# from . views import LeavesList

app_name = "hawan"

urlpatterns = [
    # path('add_participant',views.add_participant, name="add_participant" ),
    # path('', views.index, name="index"),
    path('', views.view_page, name='view_page'),
    path('district/', views.district, name='district'),
    # path('add_family_form/<int:participant_id>/',views.add_family_form,name="add_family_form"),
    path('add_family_members/<int:participant_id>/<int:num_family_members>/', views.add_family_members, name='add_family_members'),
    path('letter_hawan_current/<int:participant_id>/', views.letter_hawan_current, name='letter_hawan_current'),
    path('add_participant_with_family_members/', views.add_participant_with_family_members, name='add_participant_with_family_members'),
 ]

hawan/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count

POSITION_CHOICES = (
    ('main', 'main'),
    ('waiting', 'waiting'),
)
STATUS_CHOICES = (
    ('cancelled','cancelled'),
    ('live','live'),
)

FAMILY_MEMBERS_CHOICES = (
    ('yes', 'yes'),
    ('no', 'no'),
)
GENDER_CHOICES = (
    ('male','male'),
    ('female','female'),
    ('other','other'),
)
# class Id_Type(models.Model):
#     name = models.CharField(max_length=30)

#     def __str__(self):
#         return self.name

ID_CHOICES = (
    ('aadhar','aadhar'),
    ('voterId','voterId'),
    ('drivingLicense','drivingLicense'),
    ('passport','passport'),
    ('other','other'),
)
class Province(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']
    def __str__(self):
        return self.name

class District(models.Model):
   name = models.CharField(max_length = 100)
   province = models.ForeignKey(Province,on_delete=models.SET_NULL,blank=True,null=True,related_name='distric_province',)
   class Meta:
        ordering = ['name']
        
   def __str__(self):
       return self.name

class Event(models.Model):
    event_date = models.DateField()

    def has_excessive_participants(self):
        return (
            Participant.objects.filter(event=self, status='main').count() >= 1
            and Participant.objects.filter(event=self, status='waiting').count() >= 2
        )
    def __str__(self):
        return str(self.event_date)

class EventManager(models.Model):
    event_manager = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.event_manager.username

class Participant(models.Model):
    date_entry = models.DateTimeField(auto_now_add=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    age = models.PositiveSmallIntegerField(default=18)
    gender = models.CharField(choices=GENDER_CHOICES,max_length=6,default='male')
    phone = models.CharField(max_length=15)
    state = models.ForeignKey(Province, on_delete=models.SET_NULL, blank=True, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    village = models.CharField(max_length=100)
    type_id = models.CharField(choices=ID_CHOICES,max_length=20,default='aadhar')
    number_id = models.CharField(max_length=50)
    family_members = models.PositiveSmallIntegerField(default=0)
    position = models.CharField(choices=POSITION_CHOICES,max_length=7,default='main')
    status = models.CharField(choices=STATUS_CHOICES, max_length=9, default='live')
    registered_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)


    def __str__(self):
        return self.name

class FamilyMember(models.Model):
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(choices=GENDER_CHOICES,max_length=6,default='')
    age = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
            return self.name if self.name else "Unnamed Family Member"

hawan/forms.py
from django import forms
from .models import Participant, FamilyMember,Event
from django.db.models import Q
from datetime import datetime, time

class ParticipantForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = ['event','name','age','gender','type_id','number_id','phone','state','district','village','family_members','position','status']
        widgets = {
            'event': forms.Select(attrs={'class':'form-control'}),
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'age': forms.NumberInput(attrs={'class':'form-control','min':18,'max':120}),
            'gender': forms.Select(attrs={'class':'form-control'}),
            'type_id': forms.Select(attrs={'class':'form-control'}),
            'number_id': forms.TextInput(attrs={'class':'form-control'}),
            'phone': forms.TextInput(attrs={'class':'form-control'}),
            'state': forms.Select(attrs={'class':'form-control'}), 
            'district': forms.Select(attrs={'class':'form-control'}),
            'village': forms.TextInput(attrs={'class':'form-control'}),
            'family_members': forms.NumberInput(attrs={'class':'form-control','max':100}),
            'position': forms.Select(attrs={'class':'form-control'}),
            'status': forms.Select(attrs={'class':'form-control'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Get the current date and time
        current_datetime = datetime.now()

        # Create a datetime object with today's date and time 6:30 AM
        today_630am = datetime.combine(current_datetime.date(), time(6, 30))

        if current_datetime.time() >= time(6, 30):
            # If current time is 6:30 AM or later, exclude events before today
            excluded_events = Event.objects.filter(event_date__lte=current_datetime.date())
        else:
            # If current time is before 6:30 AM, exclude events before or equal to today
            excluded_events = Event.objects.filter(event_date__lt=current_datetime.date())

        # Exclude events with excessive participants
        excluded_event_ids = [
            event.id for event in Event.objects.all() if event.has_excessive_participants()
        ]
        excluded_events = excluded_events.union(Event.objects.filter(id__in=excluded_event_ids))

        # Get the remaining events
        filtered_events = Event.objects.exclude(id__in=excluded_events.values('id'))

        # Set the filtered events as the queryset for the event field
        self.fields['event'].queryset = filtered_events


    def clean(self):
        cleaned_data = super().clean()
        event_date = cleaned_data.get('event').event_date
        participant_position = cleaned_data.get('position')
        participant_status = cleaned_data.get('status')

        if participant_status == 'live':
            main_count = Participant.objects.filter(
                Q(position='main', status='live') | Q(position='waiting', status='live'),
                event__event_date=event_date
            ).count()
            waiting_count = Participant.objects.filter(
                position='waiting', status='live',
                event__event_date=event_date
            ).count()

            if participant_position == 'main' and main_count >= 1:
                raise forms.ValidationError("Only one participant with position 'main' allowed per event date.")
            elif participant_position == 'waiting' and waiting_count >= 2:
                raise forms.ValidationError("Only two participants with position 'waiting' allowed per event date.")    
    
class FamilyMemberForm(forms.ModelForm):
    class Meta:
        model = FamilyMember
        fields = ['name','gender','age']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'gender': forms.Select(attrs={'class':'form-control'}),
            'age': forms.NumberInput(attrs={'class':'form-control','min':1,'max':120}),
        }

hawan/views.py
from django.shortcuts import render,redirect,get_object_or_404
from . models import Participant, FamilyMember
from . forms import ParticipantForm, FamilyMemberForm
from .models import Province,District
from django.utils import timezone
from django.forms import inlineformset_factory
# from django.views import View
# Create your views here.

# def view_page(request):
#     context = {
    
#     }
#     return render(request, 'hawan/view_page.html')

# def view_page(request):
#     if request.method == 'POST':
#         form = ParticipantForm(request.POST)
#         if form.is_valid():
#             participant = form.save(commit=False)
#             participant.registered_by = request.user
#             participant.save()
#             return redirect('hawan:view_page')
#     else:
#         form = ParticipantForm()
#     context = {
#         'form':'form',
#     }
#     return render(request, 'hawan/view_page.html',context)

def district(request):
    province = request.GET.get('state')
    districts = District.objects.filter(province=province)
    context = {
        'districts':districts,
    }
    return render(request, 'partials/districts.html',context)

# def add_family_member_field(request):
#     if request.method == "POST":
#         pass

#     return render(request, 'partials/add_familymember_form.html')

# def view_page(request):
#     if request.method == 'POST':
#         form = ParticipantForm(request.POST)
#         family_member_forms = [FamilyMemberForm(request.POST, prefix=f'family_member_{i}') for i in range(5)]

#         if form.is_valid() and all([fm_form.is_valid() for fm_form in family_member_forms]):
#             participant = form.save()
#             for fm_form in family_member_forms:
#                 if fm_form.cleaned_data.get('name'):
#                     FamilyMember.objects.create(participant=participant, **fm_form.cleaned_data)
#             return redirect('hawan:view_page')  # Redirect to the desired URL upon successful submission
#     else:
#         form = ParticipantForm()
#         family_member_forms = [FamilyMemberForm(prefix=f'family_member_{i}') for i in range(5)]  # You can adjust the number of forms as needed

#     provinces = Province.objects.all()  # Assuming you have this queryset
#     context = {
#         'form': form,
#         'family_member_forms': family_member_forms,
#         'provinces': provinces,
#     }
#     return render(request, 'hawan/view_page.html', context)


def index(request):
    return render(request,'hawan/index.html')

def view_page(request):
    provinces = Province.objects.all()
    current_date = timezone.now().date()  # Get today's date
    participants = Participant.objects.filter(event__event_date__gte=current_date)
    if request.method == 'POST':
        form = ParticipantForm(request.POST)
        if form.is_valid():
            participant = form.save(commit=False)
            participant.registered_by = request.user
            participant.save()
            num_family_members = participant.family_members

            if num_family_members >= 1:
                return redirect('hawan:add_family_members', participant_id=participant.id, num_family_members=num_family_members)
            else:
                return redirect('hawan:view_page')  # Redirect to the desired view page
    else:
        form = ParticipantForm()
    context = {
        'form':form,
        'provinces':provinces,
        'participants':participants,
    }
    return render(request, 'hawan/view_page.html', context)

# def add_family_members(request, participant_id):
#     participant = get_object_or_404(Participant, id=participant_id)

#     if request.method == 'POST':
#         fm_form = FamilyMemberForm(request.POST or None)
#         if fm_form.is_valid():
#             family_member = fm_form.save(commit=False)
#             family_member.participant = participant
#             family_member.save()
#             return redirect('hawan:view_page')
#     else:
#         fm_form = FamilyMemberForm()

#     return render(request, 'partials/add_family_members.html', {
#         'participant': participant,
#         'fm_form': fm_form,
#     })

def add_family_members(request, participant_id, num_family_members):
    participant = get_object_or_404(Participant, id=participant_id)

    if request.method == 'POST':
        fm_forms = [FamilyMemberForm(request.POST, prefix=f'family_member_{i}') for i in range(num_family_members)]

        if all([fm_form.is_valid() for fm_form in fm_forms]):
            # Save the family member instances
            for fm_form in fm_forms:
                family_member = fm_form.save(commit=False)
                family_member.participant = participant
                family_member.save()

            # Redirect to the desired URL upon successful submission
            return redirect('hawan:view_page')
    else:
        fm_forms = [FamilyMemberForm(prefix=f'family_member_{i}') for i in range(num_family_members)]

    context = {
        'participant': participant,
        'fm_forms': fm_forms,
        'num_family_members': num_family_members,
    }
    return render(request, 'partials/add_family_members.html', context)

# def add_family_form(request,participant_id):
#     participant = get_object_or_404(Participant, id=participant_id)
#     if request.method == 'POST':
#         fm_form = FamilyMemberForm(request.POST or None)
#         if fm_form.is_valid():
#             family_member = fm_form.save(commit=False)
#             family_member.participant = participant
#             family_member.save()
#             return redirect('hawan:view_page')
#     else:
#         fm_form = FamilyMemberForm()
#     context = {
#         'fm_form':FamilyMemberForm(),
#         'participant': participant,
#     }
#     return render(request, 'partials/add_family_form.html',context)

def letter_hawan_current(request,participant_id):
    participant = get_object_or_404(Participant, id=participant_id)
    context = {
        'participant':participant,
    }
    return render(request, 'hawan/letter_hawan.html',context)

def add_participant_with_family_members(request):
    ParticipantFormSet = inlineformset_factory(Participant, FamilyMember, fields=('name', 'gender', 'age'))
    
    if request.method == 'POST':
        participant_form = ParticipantForm(request.POST)
        formset = ParticipantFormSet(request.POST)
        
        if participant_form.is_valid() and formset.is_valid():
            participant = participant_form.save()
            formset.instance = participant
            formset.save()
            return redirect('hawan:add_participant_with_family_members')  # Redirect to the view page
            
    else:
        participant_form = ParticipantForm()
        formset = ParticipantFormSet()
        
    context = {
        'participant_form': participant_form,
        'formset': formset,
    }
    return render(request, 'hawan/add_participant_with_family_members.html', context)

hawan/templates/partials/add_family_form.html
<form id="family-members-form" hx-post="{% url 'hawan:add_family_form' participant_id=participant.id %}"
hx-trigger="click from:#submit-all"
>
    {% csrf_token %}
    <div class="row form-group">
        <div class="col">
            {{ fm_form.name.errors }}
            <label for="{{ fm_form.name.id_for_label }}">Family Member Name</label>
            {{ fm_form.name }}
        </div>
        <div class="col align-self-end">
            {{ fm_form.gender.errors }}
            <label for="{{ fm_form.gender.id_for_label }}">Gender</label>
            {{ fm_form.gender }}
        </div>
        <div class="col align-self-end">
            {{ fm_form.age.errors }}
            <label for="{{ fm_form.age.id_for_label }}">Age</label>
            {{ fm_form.age }}
        </div>
        <div class="col align-self-end">
            <button type="button" class="btn btn-danger btn-sm"
            hx-on="click: this.closest('form').remove()"
            >Cancele</button>
        </div>   
    </div><!--End Row-->    
</form>
<script>
    document.addEventListener("htmx:afterSwap", function(evt) {
        if (evt.detail.target.id === "family-members-form") {
            const form = evt.detail.target;
            form.addEventListener("htmx:afterSettle", function() {
                if (!form.contains(document.activeElement)) {
                    window.location.href = "{% url 'hawan:view_page' %}"; // Redirect to the intended page
                }
            });
        }
    });
</script>

hawan/templates/partials/add_family_members.html
{% extends 'hawan/base.html' %}

{% block content %}
<div class="container">
    <h2 style="margin-top: 50px;">Add Family Members for {{ participant.name }}</h2>
    
    <form action="" method="POST">
        {% csrf_token %}
        <div id="family-members">
            {% for fm_form in fm_forms %}
            <div class="row">
                <div class="col-lg-4 col-md-6 mb-2">
                    {{ fm_form.name.errors }}
                    <label for="{{ fm_form.name.id_for_label }}">Family Member Name</label>
                    {{ fm_form.name }}
                </div>
                <div class="col-lg-4 col-md-6 mb-2">
                    {{ fm_form.gender.errors }}
                    <label for="{{ fm_form.gender.id_for_label }}">Gender</label>
                    {{ fm_form.gender }}
                </div>
                <div class="col-lg-4 col-md-6 mb-2">
                    {{ fm_form.age.errors }}
                    <label for="{{ fm_form.age.id_for_label }}">Age</label>
                    {{ fm_form.age }}
                </div>
            </div>
            {% endfor %}
        </div>
        
        <button type="submit" class="btn btn-primary">Add Family Members</button>
    </form>
</div>
{% endblock %}

hawan/templates/partials/add_participant.html
<div class="myform mb-5 shadow p-4">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <h3 class="text-center">Register Yazman For Hawan</h3>
    <hr>
<form action="" method="POST">
    {% csrf_token %}
    <div class="container">
        {{ form.non_field_errors }}
        <div class="row">
            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.event.errors }}
                <label for="{{ form.event.id_for_label }}">Event</label>
                {{ form.event }}
            </div>

            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.name.errors }}
                <label for="{{ form.name.id_for_label }}">Name</label>
                {{ form.name }}
            </div>
            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.gender.errors }}
                <label for="{{ form.gender.id_for_label }}">Gender</label>
                {{ form.gender }}
            </div>
            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.age.errors }}
                <label for="{{ fm_form.age.id_for_label }}">Age</label>
                {{ form.age }}
            </div>    
            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.type_id.errors }}
                <label for="{{ form.type_id.id_for_label }}">Id Type</label>
                {{ form.type_id }}
            </div>
            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.number_id.errors }}
                <label for="{{ form.number_id.id_for_label }}">Id Number</label>
                <input type="text" name="number_id" id="id_number_id" class="form-control">
            </div>
            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.phone.errors }}
                <label for="{{ form.phone.id_for_label }}">Phone Number</label>
                {{ form.phone }}
            </div>
            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.state.errors }}
                <label for="{{ form.state.id_for_label }}">State</label>
                <select name="state" id="id_state" class="form-control"
                    hx-get="{% url 'hawan:district' %}"
                    hx-trigger="change"
                    hx-target="#id_district"
                    >
                    <option selected>Select State</option>
                {% for p in provinces %}            
                        <option value="{{ p.pk }}">{{ p.name }}</option>            
                {% endfor %}
            </select>
                <!-- {{ form.province }} -->
            </div>
            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.district.errors }}
                <label for="{{ form.district.id_for_label }}">District</label>
                <div id="id_district">
                    {% include 'partials/districts.html' %}
                </div>               
                              
            </div>
            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.village.errors }}
                <label for="{{ form.village.id_for_label }}">Vill/Town/City</label>
                {{ form.village }}
            </div>
            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.family_members.errors }}
                <label for="{{ form.family_members.id_for_label }}">Family-Members</label>
                {{ form.family_members }}
            </div>

            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.position.errors }}
                <label for="{{ form.position.id_for_label }}">Position</label>
                {{ form.position }}
            </div>

            <div class="col-lg-4 col-md-6 mb-2">
                {{ form.status.errors }}
                <label for="{{ form.status.id_for_label }}">Status</label>
                {{ form.status }}
            </div>
        </div>
    </div>
    <!-- Family Member Forms -->
    <hr>
    </div>

    <div class="col-4 container">
        <input class="form-control me-2 btn btn-primary" type="submit" value="Add Yazman">
    </div>

</form>
</div>

hawan/templates/partials/districts.html
<select name="district" class="form-control">
    <option selected>Select District</option>
    {% for d in districts %}            
            <option value="{{ d.pk }}">{{ d.name }}</option>            
    {% endfor %}
</select>